### ISSUE TITLE
5. Toteutetaan kirjautuminen Lucia kirjaston avulla

### ISSUE THREAD

**Issue by samuliasmala** [samuliasmala/lahjalista#14]
Toteutetaan kirjautuminen Auth.js kirjaston avulla. Käytetään [credentials-provideria](https://authjs.dev/reference/core/providers/credentials) (eli käyttäjätunnus + salasanayhdistelmää) sekä [pg-adapteria](https://authjs.dev/reference/adapter/pg) (eli tietokantana Postgresiä).

Next.js:n sivuilta löytyy [ohje kirjautumisen tekemiseen](https://nextjs.org/learn/dashboard-app/adding-authentication), mutta en ole varma onko se täysin ajan tasalla.

**Comment by samuliasmala** [comment]
[Figmasta löytyy designit](https://www.figma.com/file/AMlMDgSf7ZLGKsLSKuZStx/Lahjalista?type=design&node-id=6-58&mode=design&t=gwu822tIQdcO2aL1-0) uuden käyttäjän luomiseen ja kirjautumiseen. Pyydän Ullaa lisäämään vielä etu- ja sukunimen rekisteröitymissivulle.

**Comment by samuliasmala** [comment]
Tehdään sittenkin Lucialla, tässä ohje [Next.js:n pages-routeriin](https://lucia-auth.com/getting-started/nextjs-pages).

**Comment by anttiasmala** [comment]
Jes, nyt on oikein. Eli `antti/authentication`-branchi on tämän `Issue`:n "korjaaja"

**Comment by samuliasmala** [comment]
> Edit: Hetkinen, onko tämä muuten huono, jos merkkaan jonkin PR:n olemaan "ratkaisija"? Hyvä kysyä jälkikäteen 😅

Ei ole huono vaan juuri oikea tapa 👍

**Comment by anttiasmala** [comment]
Tämä on toteutettu! [Kyseinen PR](#23)
