### ISSUE TITLE
13. Ei toivotun vian korjaaminen kirjautumisen suhteen

### ISSUE THREAD

**Issue by anttiasmala** [samuliasmala/lahjalista#47]
Huomasin tässä testailessa melko "vaarallisen" virheen.

Eli kun **käyttäjä_1** on kirjautunut sisään vaikka sähköpostilla `testi.teppo@email.com`. Tämän jälkeen **käyttäjä_1** kirjautuu ulos normaalisti (`auth_session`-cookie jää voimaan kekseihin)

Nyt jos **käyttäjä_2** tulee kirjautumaan sähköpostilla `testi.teppo2@email.com`. Ohjataan **käyttäjä_2** **käyttäjä_1**:n tilille, koska vanha `auth_session`-cookie on voimassa

Yksi tapa toteuttaa korjaus: kirjautuessa tarkistetaan kuuluuko `auth_session` samalle tilille mille halutaan kirjautua.
-> Jos on, ei tehdä muutoksia. 
-> Jos ei, muokataan / poistetaan vanha `auth_session` ja lisätään uusi / muokattu `auth_session`

Toteutan jonkunlaisen ratkaisun, tarkistetaan PR:ssä paremmin :+1:

**Comment by samuliasmala** [comment]
Ehdotan että aina kirjautuessa poistetaan kaikki vanhat `auth_session` cookiet.

**Comment by anttiasmala** [comment]
Hyvä idea, kiitos! Tehdään noin :+1:
